package view;

/**
 *
 * @author Carlos Esquivel
 */
public class EditorScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form EditorScreen
     */
    public EditorScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCharClass = new javax.swing.ButtonGroup();
        btnGroupWeaponClass = new javax.swing.ButtonGroup();
        javax.swing.JPanel contentPane = new javax.swing.JPanel();
        JTabbedPane = new javax.swing.JTabbedPane();
        CharactersTab = new javax.swing.JPanel();
        pnlCharSpritePreview = new javax.swing.JPanel();
        lblCharSpritePreview = new javax.swing.JLabel();
        cmBxCharAppearance = new javax.swing.JComboBox<>();
        cmBxCharAppearanceLvl = new javax.swing.JComboBox<>();
        javax.swing.JLabel lblCharAppearance = new javax.swing.JLabel();
        javax.swing.JLabel lblCharAppareanceLvl = new javax.swing.JLabel();
        javax.swing.JLabel lblCharacterClass = new javax.swing.JLabel();
        rdBtnCharClassDefault = new javax.swing.JRadioButton();
        rdBtnCharClassUser = new javax.swing.JRadioButton();
        cmBxCharClassDefault = new javax.swing.JComboBox<>();
        cmBxCharClassUser = new javax.swing.JComboBox<>();
        btnLoadCharClass = new javax.swing.JButton();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        javax.swing.JLabel lblCharAttributes = new javax.swing.JLabel();
        javax.swing.JLabel lblCharClassName = new javax.swing.JLabel();
        txtCharClassName = new javax.swing.JTextField();
        btnAddCharAppearance = new javax.swing.JButton();
        btnCreateCharObject = new javax.swing.JButton();
        btnSaveCharClass = new javax.swing.JButton();
        chkBxCharHealth = new javax.swing.JCheckBox();
        spnCharHealth = new javax.swing.JSpinner();
        chkBxCharCost = new javax.swing.JCheckBox();
        spnCharCost = new javax.swing.JSpinner();
        chkBxCharHits = new javax.swing.JCheckBox();
        spnCharHits = new javax.swing.JSpinner();
        chkBxCharTiles = new javax.swing.JCheckBox();
        spnCharTiles = new javax.swing.JSpinner();
        chkBxCharStartLvl = new javax.swing.JCheckBox();
        spnCharStartLvl = new javax.swing.JSpinner();
        chkBxCharUnlockLvl = new javax.swing.JCheckBox();
        spnCharUnlockLvl = new javax.swing.JSpinner();
        btnDelCharAppearance = new javax.swing.JButton();
        btnAddWeapon = new javax.swing.JButton();
        javax.swing.JScrollPane scrollWeapons = new javax.swing.JScrollPane();
        listWeapons = new javax.swing.JList<>();
        javax.swing.JScrollPane scrollClassWeapons = new javax.swing.JScrollPane();
        listClassWeapons = new javax.swing.JList<>();
        btnDelWeapon = new javax.swing.JButton();
        javax.swing.JLabel lblClassWeapons = new javax.swing.JLabel();
        WeaponsTab = new javax.swing.JPanel();
        pnlWeaponSpritePreview = new javax.swing.JPanel();
        lblWeaponSpritePreview = new javax.swing.JLabel();
        javax.swing.JLabel lblWeaponAppearance = new javax.swing.JLabel();
        cmBxWeaponAppearance = new javax.swing.JComboBox<>();
        javax.swing.JSeparator jSeparator3 = new javax.swing.JSeparator();
        javax.swing.JLabel lblWeaponAppareanceLvl = new javax.swing.JLabel();
        cmBxWeaponAppearanceLvl = new javax.swing.JComboBox<>();
        btnAddWeaponAppearance = new javax.swing.JButton();
        btnDelWeaponAppearance = new javax.swing.JButton();
        javax.swing.JLabel lblCharacterClass1 = new javax.swing.JLabel();
        rdBtnWeaponClassDefault = new javax.swing.JRadioButton();
        cmBxWeaponClassDefault = new javax.swing.JComboBox<>();
        cmBxWeaponClassUser = new javax.swing.JComboBox<>();
        rdBtnWeaponClassUser = new javax.swing.JRadioButton();
        btnLoadWeaponClass = new javax.swing.JButton();
        javax.swing.JSeparator jSeparator4 = new javax.swing.JSeparator();
        javax.swing.JLabel lblWeaponAttributes = new javax.swing.JLabel();
        javax.swing.JLabel lblWeaponClassName = new javax.swing.JLabel();
        txtWeaponClassName = new javax.swing.JTextField();
        chkBxWeaponDmg = new javax.swing.JCheckBox();
        spnWeaponDmg = new javax.swing.JSpinner();
        chkBxWeaponHits = new javax.swing.JCheckBox();
        spnWeaponHits = new javax.swing.JSpinner();
        spnWeaponStartLvl = new javax.swing.JSpinner();
        chkBxWeaponStartLvl = new javax.swing.JCheckBox();
        chkBxWeaponUnlockLvl = new javax.swing.JCheckBox();
        spnWeaponUnlockLvl = new javax.swing.JSpinner();
        spnWeaponAOE = new javax.swing.JSpinner();
        chkBxWeaponAOE = new javax.swing.JCheckBox();
        chkBxWeaponRange = new javax.swing.JCheckBox();
        spnWeaponRange = new javax.swing.JSpinner();
        btnSaveWeapon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Character Creation API");
        setResizable(false);

        pnlCharSpritePreview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sprite Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        pnlCharSpritePreview.setMaximumSize(new java.awt.Dimension(250, 250));
        pnlCharSpritePreview.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout pnlCharSpritePreviewLayout = new javax.swing.GroupLayout(pnlCharSpritePreview);
        pnlCharSpritePreview.setLayout(pnlCharSpritePreviewLayout);
        pnlCharSpritePreviewLayout.setHorizontalGroup(
            pnlCharSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharSpritePreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCharSpritePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCharSpritePreviewLayout.setVerticalGroup(
            pnlCharSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCharSpritePreviewLayout.createSequentialGroup()
                .addComponent(lblCharSpritePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        cmBxCharAppearance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmBxCharAppearanceLvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCharAppearance.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCharAppearance.setText("Appearance:");

        lblCharAppareanceLvl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCharAppareanceLvl.setText("Level:");

        lblCharacterClass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCharacterClass.setText("Character class");

        btnGroupCharClass.add(rdBtnCharClassDefault);
        rdBtnCharClassDefault.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rdBtnCharClassDefault.setText("Default classes:");
        rdBtnCharClassDefault.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdBtnCharClassDefaultItemStateChanged(evt);
            }
        });

        btnGroupCharClass.add(rdBtnCharClassUser);
        rdBtnCharClassUser.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rdBtnCharClassUser.setText("User defined:");
        rdBtnCharClassUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdBtnCharClassUserItemStateChanged(evt);
            }
        });

        cmBxCharClassDefault.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmBxCharClassUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmBxCharClassUser.setEnabled(false);

        btnLoadCharClass.setText("Load Character Class Info");
        btnLoadCharClass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator1.setForeground(new java.awt.Color(187, 187, 187));

        jSeparator2.setForeground(new java.awt.Color(187, 187, 187));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(10, 50));

        lblCharAttributes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCharAttributes.setText("Attributes");

        lblCharClassName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCharClassName.setText("Class name:");

        txtCharClassName.setToolTipText("Class Name");

        btnAddCharAppearance.setText("Add New Character Appearance");

        btnCreateCharObject.setText("Create Character Object");
        btnCreateCharObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCharObjectActionPerformed(evt);
            }
        });

        btnSaveCharClass.setText("Save Character Class");

        chkBxCharHealth.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxCharHealth.setSelected(true);
        chkBxCharHealth.setText("Max Health Points (HP):");
        chkBxCharHealth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxCharHealthItemStateChanged(evt);
            }
        });

        chkBxCharCost.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxCharCost.setSelected(true);
        chkBxCharCost.setText("Production Cost:");
        chkBxCharCost.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxCharCostItemStateChanged(evt);
            }
        });

        chkBxCharHits.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxCharHits.setSelected(true);
        chkBxCharHits.setText("Hits per Time unit:");
        chkBxCharHits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxCharHitsItemStateChanged(evt);
            }
        });

        chkBxCharTiles.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxCharTiles.setSelected(true);
        chkBxCharTiles.setText("Tile Hitbox:");
        chkBxCharTiles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxCharTilesItemStateChanged(evt);
            }
        });

        chkBxCharStartLvl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxCharStartLvl.setSelected(true);
        chkBxCharStartLvl.setText("Starting Level:");
        chkBxCharStartLvl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxCharStartLvlItemStateChanged(evt);
            }
        });

        chkBxCharUnlockLvl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxCharUnlockLvl.setSelected(true);
        chkBxCharUnlockLvl.setText("Unlocking Level:");
        chkBxCharUnlockLvl.setToolTipText("");
        chkBxCharUnlockLvl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxCharUnlockLvlItemStateChanged(evt);
            }
        });

        btnDelCharAppearance.setText("Delete Selected Character Appearance");

        btnAddWeapon.setText(">");
        btnAddWeapon.setEnabled(false);
        btnAddWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWeaponActionPerformed(evt);
            }
        });

        listWeapons.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listWeapons.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listWeapons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listWeapons.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWeaponsValueChanged(evt);
            }
        });
        scrollWeapons.setViewportView(listWeapons);

        listClassWeapons.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listClassWeapons.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listClassWeapons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listClassWeapons.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listClassWeaponsValueChanged(evt);
            }
        });
        scrollClassWeapons.setViewportView(listClassWeapons);

        btnDelWeapon.setText("X");
        btnDelWeapon.setEnabled(false);

        lblClassWeapons.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClassWeapons.setText("Weapons:");

        javax.swing.GroupLayout CharactersTabLayout = new javax.swing.GroupLayout(CharactersTab);
        CharactersTab.setLayout(CharactersTabLayout);
        CharactersTabLayout.setHorizontalGroup(
            CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharactersTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CharactersTabLayout.createSequentialGroup()
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(CharactersTabLayout.createSequentialGroup()
                                    .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rdBtnCharClassDefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdBtnCharClassUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmBxCharClassDefault, 0, 140, Short.MAX_VALUE)
                                        .addComponent(cmBxCharClassUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(lblCharAttributes)
                                .addComponent(btnLoadCharClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblCharacterClass)
                            .addComponent(lblClassWeapons)
                            .addGroup(CharactersTabLayout.createSequentialGroup()
                                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CharactersTabLayout.createSequentialGroup()
                                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CharactersTabLayout.createSequentialGroup()
                                                .addComponent(lblCharClassName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCharClassName))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CharactersTabLayout.createSequentialGroup()
                                                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkBxCharHits, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(chkBxCharHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spnCharHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(spnCharHits))))
                                        .addGap(18, 18, 18)
                                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkBxCharTiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chkBxCharCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chkBxCharUnlockLvl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CharactersTabLayout.createSequentialGroup()
                                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CharactersTabLayout.createSequentialGroup()
                                                .addComponent(scrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnAddWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnDelWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(scrollClassWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CharactersTabLayout.createSequentialGroup()
                                                .addComponent(chkBxCharStartLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(spnCharStartLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(174, 174, 174)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnCharCost, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCharTiles, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCharUnlockLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCharSpritePreview, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addGroup(CharactersTabLayout.createSequentialGroup()
                                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCharAppearance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCharAppareanceLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmBxCharAppearance, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmBxCharAppearanceLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAddCharAppearance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelCharAppearance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CharactersTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveCharClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateCharObject)))
                .addContainerGap())
        );
        CharactersTabLayout.setVerticalGroup(
            CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharactersTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CharactersTabLayout.createSequentialGroup()
                        .addComponent(lblCharacterClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdBtnCharClassDefault)
                            .addComponent(cmBxCharClassDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdBtnCharClassUser)
                            .addComponent(cmBxCharClassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadCharClass)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCharAttributes)
                        .addGap(18, 18, 18)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCharClassName)
                            .addComponent(txtCharClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBxCharHealth)
                            .addComponent(spnCharCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxCharCost)
                            .addComponent(spnCharHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnCharHits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxCharHits)
                            .addComponent(spnCharTiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxCharTiles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnCharStartLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxCharStartLvl)
                            .addComponent(spnCharUnlockLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxCharUnlockLvl))
                        .addGap(18, 18, 18)
                        .addComponent(lblClassWeapons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollClassWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CharactersTabLayout.createSequentialGroup()
                                .addComponent(btnAddWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelWeapon))
                            .addComponent(scrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CharactersTabLayout.createSequentialGroup()
                        .addComponent(pnlCharSpritePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmBxCharAppearance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCharAppearance))
                        .addGap(6, 6, 6)
                        .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmBxCharAppearanceLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCharAppareanceLvl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddCharAppearance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelCharAppearance))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CharactersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCharObject)
                    .addComponent(btnSaveCharClass))
                .addContainerGap())
        );

        JTabbedPane.addTab("Characters", CharactersTab);

        pnlWeaponSpritePreview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sprite Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        pnlWeaponSpritePreview.setMaximumSize(new java.awt.Dimension(250, 250));
        pnlWeaponSpritePreview.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout pnlWeaponSpritePreviewLayout = new javax.swing.GroupLayout(pnlWeaponSpritePreview);
        pnlWeaponSpritePreview.setLayout(pnlWeaponSpritePreviewLayout);
        pnlWeaponSpritePreviewLayout.setHorizontalGroup(
            pnlWeaponSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWeaponSpritePreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWeaponSpritePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlWeaponSpritePreviewLayout.setVerticalGroup(
            pnlWeaponSpritePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWeaponSpritePreviewLayout.createSequentialGroup()
                .addComponent(lblWeaponSpritePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        lblWeaponAppearance.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWeaponAppearance.setText("Appearance:");

        cmBxWeaponAppearance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator3.setForeground(new java.awt.Color(187, 187, 187));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 50));

        lblWeaponAppareanceLvl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWeaponAppareanceLvl.setText("Level:");

        cmBxWeaponAppearanceLvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddWeaponAppearance.setText("Add New Weapon Appearance");

        btnDelWeaponAppearance.setText("Delete Selected Weapon Appearance");

        lblCharacterClass1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCharacterClass1.setText("Weapon class");

        btnGroupCharClass.add(rdBtnWeaponClassDefault);
        rdBtnWeaponClassDefault.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rdBtnWeaponClassDefault.setText("Default classes:");
        rdBtnWeaponClassDefault.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdBtnWeaponClassDefaultItemStateChanged(evt);
            }
        });

        cmBxWeaponClassDefault.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmBxWeaponClassUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmBxWeaponClassUser.setEnabled(false);

        btnGroupCharClass.add(rdBtnWeaponClassUser);
        rdBtnWeaponClassUser.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rdBtnWeaponClassUser.setText("User defined:");
        rdBtnWeaponClassUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdBtnWeaponClassUserItemStateChanged(evt);
            }
        });

        btnLoadWeaponClass.setText("Load Weapon Class Info");
        btnLoadWeaponClass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator4.setForeground(new java.awt.Color(187, 187, 187));

        lblWeaponAttributes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWeaponAttributes.setText("Attributes");

        lblWeaponClassName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblWeaponClassName.setText("Weapon name:");

        txtWeaponClassName.setToolTipText("Class Name");

        chkBxWeaponDmg.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxWeaponDmg.setSelected(true);
        chkBxWeaponDmg.setText("Weapon Damage:");
        chkBxWeaponDmg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxWeaponDmgItemStateChanged(evt);
            }
        });

        chkBxWeaponHits.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxWeaponHits.setSelected(true);
        chkBxWeaponHits.setText("Hits per Time unit:");
        chkBxWeaponHits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxWeaponHitsItemStateChanged(evt);
            }
        });

        chkBxWeaponStartLvl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxWeaponStartLvl.setSelected(true);
        chkBxWeaponStartLvl.setText("Starting Level:");
        chkBxWeaponStartLvl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxWeaponStartLvlItemStateChanged(evt);
            }
        });

        chkBxWeaponUnlockLvl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxWeaponUnlockLvl.setSelected(true);
        chkBxWeaponUnlockLvl.setText("Unlocking Level:");
        chkBxWeaponUnlockLvl.setToolTipText("");
        chkBxWeaponUnlockLvl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxWeaponUnlockLvlItemStateChanged(evt);
            }
        });

        chkBxWeaponAOE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxWeaponAOE.setSelected(true);
        chkBxWeaponAOE.setText("Area of Effect:");
        chkBxWeaponAOE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxWeaponAOEItemStateChanged(evt);
            }
        });

        chkBxWeaponRange.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkBxWeaponRange.setSelected(true);
        chkBxWeaponRange.setText("Attack Range:");
        chkBxWeaponRange.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBxWeaponRangeItemStateChanged(evt);
            }
        });

        btnSaveWeapon.setText("Save Weapon");

        javax.swing.GroupLayout WeaponsTabLayout = new javax.swing.GroupLayout(WeaponsTab);
        WeaponsTab.setLayout(WeaponsTabLayout);
        WeaponsTabLayout.setHorizontalGroup(
            WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WeaponsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WeaponsTabLayout.createSequentialGroup()
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WeaponsTabLayout.createSequentialGroup()
                                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(WeaponsTabLayout.createSequentialGroup()
                                        .addComponent(lblWeaponClassName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtWeaponClassName))
                                    .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(WeaponsTabLayout.createSequentialGroup()
                                            .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(chkBxWeaponHits, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(chkBxWeaponDmg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(spnWeaponDmg, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(spnWeaponHits)))
                                        .addGroup(WeaponsTabLayout.createSequentialGroup()
                                            .addComponent(chkBxWeaponStartLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spnWeaponStartLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBxWeaponAOE, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkBxWeaponRange, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkBxWeaponUnlockLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnWeaponRange, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnWeaponAOE, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnWeaponUnlockLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(WeaponsTabLayout.createSequentialGroup()
                                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rdBtnWeaponClassDefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdBtnWeaponClassUser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmBxWeaponClassDefault, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmBxWeaponClassUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnLoadWeaponClass, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCharacterClass1)
                            .addComponent(lblWeaponAttributes)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WeaponsTabLayout.createSequentialGroup()
                                .addComponent(lblWeaponAppearance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(cmBxWeaponAppearance, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlWeaponSpritePreview, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addGroup(WeaponsTabLayout.createSequentialGroup()
                                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddWeaponAppearance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelWeaponAppearance, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(WeaponsTabLayout.createSequentialGroup()
                                .addComponent(lblWeaponAppareanceLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmBxWeaponAppearanceLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WeaponsTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveWeapon)))
                .addContainerGap())
        );
        WeaponsTabLayout.setVerticalGroup(
            WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WeaponsTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(WeaponsTabLayout.createSequentialGroup()
                        .addComponent(lblCharacterClass1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdBtnWeaponClassDefault)
                            .addComponent(cmBxWeaponClassDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdBtnWeaponClassUser)
                            .addComponent(cmBxWeaponClassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadWeaponClass)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWeaponAttributes)
                        .addGap(18, 18, 18)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeaponClassName)
                            .addComponent(txtWeaponClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBxWeaponDmg)
                            .addComponent(spnWeaponRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxWeaponRange)
                            .addComponent(spnWeaponDmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnWeaponHits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxWeaponHits)
                            .addComponent(spnWeaponAOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxWeaponAOE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnWeaponStartLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxWeaponStartLvl)
                            .addComponent(spnWeaponUnlockLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBxWeaponUnlockLvl)))
                    .addGroup(WeaponsTabLayout.createSequentialGroup()
                        .addComponent(pnlWeaponSpritePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmBxWeaponAppearance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWeaponAppearance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WeaponsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmBxWeaponAppearanceLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWeaponAppareanceLvl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddWeaponAppearance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelWeaponAppearance))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(btnSaveWeapon)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Weapons", WeaponsTab);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listClassWeaponsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listClassWeaponsValueChanged
        btnDelWeapon.setEnabled(listClassWeapons.getSelectedIndex() > -1);
    }//GEN-LAST:event_listClassWeaponsValueChanged

    private void listWeaponsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWeaponsValueChanged
        btnAddWeapon.setEnabled(listWeapons.getSelectedIndex() > -1);
    }//GEN-LAST:event_listWeaponsValueChanged

    private void chkBxCharUnlockLvlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxCharUnlockLvlItemStateChanged
        spnCharUnlockLvl.setEnabled(chkBxCharUnlockLvl.isSelected());
    }//GEN-LAST:event_chkBxCharUnlockLvlItemStateChanged

    private void chkBxCharStartLvlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxCharStartLvlItemStateChanged
        spnCharStartLvl.setEnabled(chkBxCharStartLvl.isSelected());
    }//GEN-LAST:event_chkBxCharStartLvlItemStateChanged

    private void chkBxCharTilesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxCharTilesItemStateChanged
        spnCharTiles.setEnabled(chkBxCharTiles.isSelected());
    }//GEN-LAST:event_chkBxCharTilesItemStateChanged

    private void chkBxCharHitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxCharHitsItemStateChanged
        spnCharHits.setEnabled(chkBxCharHits.isSelected());
    }//GEN-LAST:event_chkBxCharHitsItemStateChanged

    private void chkBxCharCostItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxCharCostItemStateChanged
        spnCharCost.setEnabled(chkBxCharCost.isSelected());
    }//GEN-LAST:event_chkBxCharCostItemStateChanged

    private void chkBxCharHealthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxCharHealthItemStateChanged
        spnCharHealth.setEnabled(chkBxCharHealth.isSelected());
    }//GEN-LAST:event_chkBxCharHealthItemStateChanged

    private void rdBtnCharClassUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdBtnCharClassUserItemStateChanged
        cmBxCharClassUser.setEnabled(rdBtnCharClassUser.isSelected());
    }//GEN-LAST:event_rdBtnCharClassUserItemStateChanged

    private void rdBtnCharClassDefaultItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdBtnCharClassDefaultItemStateChanged
        cmBxCharClassDefault.setEnabled(rdBtnCharClassDefault.isSelected());
    }//GEN-LAST:event_rdBtnCharClassDefaultItemStateChanged

    private void rdBtnWeaponClassDefaultItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdBtnWeaponClassDefaultItemStateChanged
        cmBxWeaponClassDefault.setEnabled(rdBtnWeaponClassDefault.isSelected());
    }//GEN-LAST:event_rdBtnWeaponClassDefaultItemStateChanged

    private void rdBtnWeaponClassUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdBtnWeaponClassUserItemStateChanged
        cmBxWeaponClassUser.setEnabled(rdBtnWeaponClassUser.isSelected());
    }//GEN-LAST:event_rdBtnWeaponClassUserItemStateChanged

    private void chkBxWeaponDmgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxWeaponDmgItemStateChanged
        spnWeaponDmg.setEnabled(chkBxWeaponDmg.isSelected());
    }//GEN-LAST:event_chkBxWeaponDmgItemStateChanged

    private void chkBxWeaponHitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxWeaponHitsItemStateChanged
        spnWeaponHits.setEnabled(chkBxWeaponHits.isSelected());
    }//GEN-LAST:event_chkBxWeaponHitsItemStateChanged

    private void chkBxWeaponStartLvlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxWeaponStartLvlItemStateChanged
        spnWeaponStartLvl.setEnabled(chkBxWeaponStartLvl.isSelected());
    }//GEN-LAST:event_chkBxWeaponStartLvlItemStateChanged

    private void chkBxWeaponUnlockLvlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxWeaponUnlockLvlItemStateChanged
        spnWeaponUnlockLvl.setEnabled(chkBxWeaponUnlockLvl.isSelected());
    }//GEN-LAST:event_chkBxWeaponUnlockLvlItemStateChanged

    private void chkBxWeaponAOEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxWeaponAOEItemStateChanged
        spnWeaponAOE.setEnabled(chkBxWeaponAOE.isSelected());
    }//GEN-LAST:event_chkBxWeaponAOEItemStateChanged

    private void chkBxWeaponRangeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBxWeaponRangeItemStateChanged
        spnWeaponRange.setEnabled(chkBxWeaponRange.isSelected());
    }//GEN-LAST:event_chkBxWeaponRangeItemStateChanged

    private void btnCreateCharObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCharObjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateCharObjectActionPerformed

    private void btnAddWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWeaponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddWeaponActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CharactersTab;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JPanel WeaponsTab;
    protected javax.swing.JButton btnAddCharAppearance;
    protected javax.swing.JButton btnAddWeapon;
    protected javax.swing.JButton btnAddWeaponAppearance;
    protected javax.swing.JButton btnCreateCharObject;
    protected javax.swing.JButton btnDelCharAppearance;
    protected javax.swing.JButton btnDelWeapon;
    protected javax.swing.JButton btnDelWeaponAppearance;
    private javax.swing.ButtonGroup btnGroupCharClass;
    private javax.swing.ButtonGroup btnGroupWeaponClass;
    protected javax.swing.JButton btnLoadCharClass;
    protected javax.swing.JButton btnLoadWeaponClass;
    protected javax.swing.JButton btnSaveCharClass;
    protected javax.swing.JButton btnSaveWeapon;
    protected javax.swing.JCheckBox chkBxCharCost;
    protected javax.swing.JCheckBox chkBxCharHealth;
    protected javax.swing.JCheckBox chkBxCharHits;
    protected javax.swing.JCheckBox chkBxCharStartLvl;
    protected javax.swing.JCheckBox chkBxCharTiles;
    protected javax.swing.JCheckBox chkBxCharUnlockLvl;
    protected javax.swing.JCheckBox chkBxWeaponAOE;
    protected javax.swing.JCheckBox chkBxWeaponDmg;
    protected javax.swing.JCheckBox chkBxWeaponHits;
    protected javax.swing.JCheckBox chkBxWeaponRange;
    protected javax.swing.JCheckBox chkBxWeaponStartLvl;
    protected javax.swing.JCheckBox chkBxWeaponUnlockLvl;
    protected javax.swing.JComboBox<String> cmBxCharAppearance;
    protected javax.swing.JComboBox<String> cmBxCharAppearanceLvl;
    protected javax.swing.JComboBox<String> cmBxCharClassDefault;
    protected javax.swing.JComboBox<String> cmBxCharClassUser;
    protected javax.swing.JComboBox<String> cmBxWeaponAppearance;
    protected javax.swing.JComboBox<String> cmBxWeaponAppearanceLvl;
    protected javax.swing.JComboBox<String> cmBxWeaponClassDefault;
    protected javax.swing.JComboBox<String> cmBxWeaponClassUser;
    protected javax.swing.JLabel lblCharSpritePreview;
    protected javax.swing.JLabel lblWeaponSpritePreview;
    protected javax.swing.JList<String> listClassWeapons;
    protected javax.swing.JList<String> listWeapons;
    protected javax.swing.JPanel pnlCharSpritePreview;
    protected javax.swing.JPanel pnlWeaponSpritePreview;
    protected javax.swing.JRadioButton rdBtnCharClassDefault;
    protected javax.swing.JRadioButton rdBtnCharClassUser;
    protected javax.swing.JRadioButton rdBtnWeaponClassDefault;
    protected javax.swing.JRadioButton rdBtnWeaponClassUser;
    protected javax.swing.JSpinner spnCharCost;
    protected javax.swing.JSpinner spnCharHealth;
    protected javax.swing.JSpinner spnCharHits;
    protected javax.swing.JSpinner spnCharStartLvl;
    protected javax.swing.JSpinner spnCharTiles;
    protected javax.swing.JSpinner spnCharUnlockLvl;
    protected javax.swing.JSpinner spnWeaponAOE;
    protected javax.swing.JSpinner spnWeaponDmg;
    protected javax.swing.JSpinner spnWeaponHits;
    protected javax.swing.JSpinner spnWeaponRange;
    protected javax.swing.JSpinner spnWeaponStartLvl;
    protected javax.swing.JSpinner spnWeaponUnlockLvl;
    protected javax.swing.JTextField txtCharClassName;
    protected javax.swing.JTextField txtWeaponClassName;
    // End of variables declaration//GEN-END:variables
}
